from __future__ import annotations

from datetime import datetime, timezone

DISPATCH_MODE_IMMEDIATE = "immediate"
DISPATCH_MODE_SCHEDULED = "scheduled"

NOTIFICATION_STATUS_PENDING = "pending"
NOTIFICATION_STATUS_QUEUED = "queued"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_SKIPPED = "skipped"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_STATUS_BOUNCED = "bounced"
NOTIFICATION_STATUS_CANCELLED = "cancelled"

CHANNEL_EMAIL = "email"
CHANNEL_SMS = "sms"

NOTIFICATION_TYPE_REMINDER_EMAIL = "reminder_email"
NOTIFICATION_TYPE_REMINDER_SMS = "reminder_sms"
NOTIFICATION_TYPE_CLIENT_BOOKING_CONFIRMATION = "client_booking_confirmation"
NOTIFICATION_TYPE_ADMIN_BOOKING_CONFIRMATION = "admin_booking_confirmation"
NOTIFICATION_TYPE_CLIENT_BOOKING_CANCELLATION = "client_booking_cancellation"
NOTIFICATION_TYPE_ADMIN_BOOKING_CANCELLATION = "admin_booking_cancellation"
NOTIFICATION_TYPE_ADMIN_SLOT_CANCELLATION = "admin_slot_cancellation"
NOTIFICATION_TYPE_ADMIN_BANK_TRANSFER_REVIEW = "admin_bank_transfer_review"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_SUCCESS_CUSTOMER = "subscription_payment_success_customer"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_SUCCESS_ADMIN = "subscription_payment_success_admin"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FIRST_CUSTOMER = "subscription_payment_failed_first_customer"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FIRST_ADMIN = "subscription_payment_failed_first_admin"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FINAL_CUSTOMER = "subscription_payment_failed_final_customer"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FINAL_ADMIN = "subscription_payment_failed_final_admin"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_RECOVERED_CUSTOMER = "subscription_payment_recovered_customer"
NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_RECOVERED_ADMIN = "subscription_payment_recovered_admin"
NOTIFICATION_TYPE_ADMIN_QUOTES_EXPIRING_TODAY = "admin_quotes_expiring_today"

IMMEDIATE_NOTIFICATION_TYPES = {
    NOTIFICATION_TYPE_CLIENT_BOOKING_CONFIRMATION,
    NOTIFICATION_TYPE_ADMIN_BOOKING_CONFIRMATION,
    NOTIFICATION_TYPE_CLIENT_BOOKING_CANCELLATION,
    NOTIFICATION_TYPE_ADMIN_BOOKING_CANCELLATION,
    NOTIFICATION_TYPE_ADMIN_SLOT_CANCELLATION,
    NOTIFICATION_TYPE_ADMIN_BANK_TRANSFER_REVIEW,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_SUCCESS_CUSTOMER,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_SUCCESS_ADMIN,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FIRST_CUSTOMER,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FIRST_ADMIN,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FINAL_CUSTOMER,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_FAILED_FINAL_ADMIN,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_RECOVERED_CUSTOMER,
    NOTIFICATION_TYPE_SUBSCRIPTION_PAYMENT_RECOVERED_ADMIN,
    NOTIFICATION_TYPE_ADMIN_QUOTES_EXPIRING_TODAY,
}

SCHEDULED_NOTIFICATION_TYPES = {
    NOTIFICATION_TYPE_REMINDER_EMAIL,
    NOTIFICATION_TYPE_REMINDER_SMS,
}

EVENT_BOOKING_CREATED_FROM_CLIENT_PORTAL = "booking_created_from_client_portal"
EVENT_BOOKING_CANCELLED_FROM_CLIENT_PORTAL = "booking_cancelled_from_client_portal"
EVENT_SLOT_CANCELLED = "slot_cancelled"
EVENT_BOOKING_REMINDER_DUE = "booking_reminder_due"
EVENT_EMAIL_BOUNCED = "email_bounced"
EVENT_SMS_DELIVERY_FAILED_PERMANENT = "sms_delivery_failed_permanent"
EVENT_SUBSCRIPTION_BILLING_CYCLE_CREATED = "subscription_billing_cycle_created"
EVENT_SUBSCRIPTION_PAYMENT_SUCCESS = "subscription_payment_success"
EVENT_SUBSCRIPTION_PAYMENT_FAILED_FIRST = "subscription_payment_failed_first"
EVENT_SUBSCRIPTION_PAYMENT_FAILED_FINAL = "subscription_payment_failed_final"
EVENT_SUBSCRIPTION_PAYMENT_RECOVERED = "subscription_payment_recovered"

SOURCE_CLIENT_PORTAL = "client_portal"
SOURCE_ADMIN_BO = "admin_bo"
SOURCE_SYSTEM = "system"
SOURCE_SCHEDULER = "scheduler"
SOURCE_PROVIDER_WEBHOOK = "provider_webhook"
SOURCE_API = "api"

QUEUE_NOTIFICATIONS_IMMEDIATE = "notifications_immediate"
QUEUE_NOTIFICATIONS_SCHEDULED = "notifications_scheduled"
QUEUE_DELIVERY_FEEDBACK = "delivery_feedback"
QUEUE_MONITORING_MAINTENANCE = "monitoring_maintenance"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)
